- name: Deploy ECS task definition and service
  hosts: localhost

  tasks:
    - set_fact: EcsClusterName="YOUR_CLUSTER"
    - name: create task def- from ansible
      ecs_taskdefinition:
        containers:
        - name: wordpress
          cpu: 10
          essential: true
          image: "wordpress"
          memory: 500
          links:
          - mysql         
          portMappings:
          - containerPort: 80
            hostPort: 80
        - name: phpmyadmin
          cpu: 10
          essential: true
          image: "corbinu/docker-phpmyadmin"
          memory: 500
          links:
          - mysql         
          environment:
          - name: "MYSQL_ROOT_PASSWORD"
            value: "password"
          - name: "MYSQL_USERNAME"
            value: "root"
          portMappings:
          - containerPort: 80
            hostPort: 8181
        - name: mysql
          cpu: 10
          essential: true
          image: "mysql"
          memory: 500                  
          environment:
          - name: "MYSQL_ROOT_PASSWORD"
            value: "password"
        state: present
        family: wordpress_from_ansible
        # revision: 1
      register: task_output    
   
    - name: Print details name      
      debug: var=task_output.taskdefinition["family"]
    - name: Print details Task revision     
      debug: var=task_output.taskdefinition["revision"]
    - name: Print details Task name and revision     
      debug: 
        msg: "{{  task_output.taskdefinition[\"family\"]   }}:{{ task_output.taskdefinition[\"revision\"] }}"
    
    - name: create ecs service
      ecs_service:
        state: present
        name: wordpress_from_ansible
        cluster: "{{EcsClusterName}}"
        task_definition: "{{  task_output.taskdefinition[\"family\"]   }}:{{ task_output.taskdefinition[\"revision\"] }}"
        desired_count: 1       
      register: service_output
    
    - name: Service Status     
      debug: var=service_output.service.status
    
    - name: Service name 
      debug: var=service_output.service.serviceName

    - name: Service ARN
      debug: var=service_output.service.serviceArn

    - name: Cluster ARN 
      debug: var=service_output.service.clusterArn         